# docker-compose.yml (Final Production-Ready Version)
version: '3.8'

services:
  backend:
    build: ./backend
    # We no longer need to expose the backend port to the host machine,
    # as Nginx will talk to it directly inside the Docker network.
    # ports:
    #   - "8000:8000" 
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      # We map your computer's port 80 to the container's port 80 (Nginx)
      - "80:80"
    # We don't need volumes for production builds, but they are useful for dev
    # volumes:
    #   - ./frontend/vite-project:/app