# docker-compose.yml
services:
  backend:
    build: ./backend
    ports:
      # Map your computer's port 8000 to the container's port 8000
      - "8000:8000"
    volumes:
      # Mount your local backend code into the container for hot-reloading
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      # Map your computer's port 5173 to the container's port 5173
      - "5173:5173"
    volumes:
      # Mount your local frontend code for hot-reloading
      - ./frontend:/app
      # Prevents node_modules from being overwritten by the local empty folder
      - /app/node_modules
    environment:
      # --- THE MAGIC OF DOCKER NETWORKING ---
      # The frontend can now reach the backend using its service name "backend"
      - VITE_API_BASE_URL=http://backend:8000
    env_file:
      - ./frontend/.env.local